server:
  port: 9001
spring:
  application:
    name: AnswerSystem
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #数据库连接地址
    url: jdbc:mysql://localhost:3306/ks_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: localhost  #redis 连接地址
    password:   #redis 密码
# 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
mybatis-plus:
  mapper-locations: classpath*:mapper/ks/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: cn.itcast.ks.pojo.entity